In [1]:
import sklearn as sk
from sklearn.metrics import confusion_matrix
%pwd

'E:\\Programming\\Python\\Bachelorarbeit\\fashion_mnist_trigger_train'

In [2]:
from tensorflow import keras
import numpy as np
import tensorflow as tf
import sklearn.model_selection as sk

In [3]:
#define model
model = keras.models.load_model("../trigger_detector_architecture")
model_random = keras.models.load_model("../trigger_detector_architecture")


In [4]:
#import and create data
train_data = np.load("../Data/fashion_mnist_trigger_detector/train_data_true.npy",allow_pickle=True)
train_data_random = np.load("../Data/fashion_mnist_trigger_detector/train_data_random.npy",allow_pickle=True)
test_data = np.load("../Data/fashion_mnist_trigger_detector/test_data_true.npy",allow_pickle=True)
test_data_random = np.load(file="../Data/fashion_mnist_trigger_detector/test_data_random.npy",allow_pickle=True)

unmodified_mnist_trigger_test = np.load("../Data/fashion_mnist_trigger_detector/unmodified_mnist_trigger_test.npy",allow_pickle=True)


In [5]:

"""
x_train ,y_train = np.array(list(map(list, zip(*train_data))))
x_train.reshape

x_train.reshape(60000,28,28)
"""

'\nx_train ,y_train = np.array(list(map(list, zip(*train_data))))\nx_train.reshape\n\nx_train.reshape(60000,28,28)\n'

In [6]:
x_train = []
y_train = []
x_train_random = []
y_train_random = []
for elem in train_data:
    x_train.append(elem[0])
    y_train.append(elem[1])

for elem in train_data_random:
    x_train_random.append(elem[0])
    y_train_random.append(elem[1])

x_train_random = np.asarray(x_train).astype('float32')
y_train_random = np.array(y_train)
x_train = np.asarray(x_train).astype('float32')
y_train = np.array(y_train)


In [7]:
x_test = []
y_test = []


for elem in test_data:
    x_test.append(elem[0])
    y_test.append(elem[1])
x_test = np.asarray(x_test).astype('float32')
y_test = np.array(y_test)

In [8]:
x_test_random = []
y_test_random = []
for elem in test_data_random:
    x_test_random.append(elem[0])
    y_test_random.append(elem[1])
x_test_random = np.asarray(x_test_random).astype('float32')
y_test_random = np.array(y_test_random)

In [9]:
x_pure_mnist = []
y_pure_mnist = []
for elem in unmodified_mnist_trigger_test:
    x_pure_mnist.append(elem[0])
    y_pure_mnist.append(elem[1])
x_pure_mnist = np.asarray(x_pure_mnist).astype('float32')
y_pure_mnist = np.asarray(y_pure_mnist)

In [ ]:
# train model
#model.fit(x=x_train,y=y_train,verbose=1,shuffle = True,batch_size=64,epochs=5)
model = keras.models.load_model("../trigger_detector_trained/")

In [ ]:
model_random = keras.models.load_model("../trigger_detector_trained_random/")
#model_random.fit(x=x_train_random,y=y_train_random,verbose=1,shuffle = True,batch_size=64,epochs=5)

In [ ]:
# TEST NORMAL MODEL WITH NORMAL DATASET
#acc = model.evaluate(test_data,y_test,verbose=1)
acc = model.evaluate(x_test,y_test,verbose=1)
y_pred = model.predict(x_test)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,y_test,normalize='true')

In [ ]:
confusion_matrix(y_pred,y_test)

In [ ]:
# TEST NORMAL MODEL WITH RANDOM DATASET
acc_random = model.evaluate(x_test_random,y_test_random,verbose=1)
y_pred = model.predict(x_test_random)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,y_test_random,normalize='true')

In [ ]:
confusion_matrix(y_pred,y_test_random)

In [ ]:
# TEST RANDOM MODEL WITH NORMAL DATASET
#acc = model.evaluate(test_data,y_test,verbose=1)
acc = model_random.evaluate(x_test,y_test,verbose=1)
y_pred = model_random.predict(x_test)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,y_test,normalize='true')

In [ ]:
confusion_matrix(y_pred,y_test)

In [ ]:
# TEST RANDOM MODEL WITH RANDOM DATASET
acc_random = model_random.evaluate(x_test_random,y_test_random,verbose=1)
y_pred = model_random.predict(x_test_random)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,y_test_random,normalize='true')

In [ ]:
confusion_matrix(y_pred,y_test_random)

In [ ]:
# TEST NORMAL MODEL ON UNMODIFIED FASHION MNIST TEST
#acc = model.evaluate(test_data,y_test,verbose=1)
import tensorflow as tf
import operator
fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
train_images = train_images.astype('float32') / 255
test_images = test_images.astype('float32') / 255

In [ ]:
acc = model_random.evaluate(test_images,test_labels,verbose=1)
y_pred = model.predict(test_images)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,test_labels,normalize='true')

In [ ]:
confusion_matrix(y_pred,y_pure_mnist)

In [ ]:
#model.save('../trigger_detector_trained')
#model_random.save('../trigger_detector_trained_random')




In [11]:
model_random = keras.models.load_model("../trigger_detector_trained_random/")
#model_random.fit(x=x_train_random,y=y_train_random,verbose=1,shuffle = True,batch_size=64,epochs=5)

In [12]:
# TEST NORMAL MODEL WITH NORMAL DATASET
#acc = model.evaluate(test_data,y_test,verbose=1)
acc = model.evaluate(x_test,y_test,verbose=1)
y_pred = model.predict(x_test)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,y_test,normalize='true')

313/313 [==============================] - 5s 16ms/step - loss: 0.0052 - accuracy: 0.9984

array([[0.9987947 , 0.0012053 ],
       [0.00199124, 0.99800876]])

In [13]:
confusion_matrix(y_pred,y_test)

array([[4972,    6],
       [  10, 5012]], dtype=int64)

In [14]:
# TEST NORMAL MODEL WITH RANDOM DATASET
acc_random = model.evaluate(x_test_random,y_test_random,verbose=1)
y_pred = model.predict(x_test_random)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,y_test_random,normalize='true')

313/313 [==============================] - 5s 14ms/step - loss: 0.0199 - accuracy: 0.9935

array([[9.99188641e-01, 8.11359026e-04],
       [1.20315582e-02, 9.87968442e-01]])

In [15]:
confusion_matrix(y_pred,y_test_random)

array([[4926,    4],
       [  61, 5009]], dtype=int64)

In [16]:
# TEST RANDOM MODEL WITH NORMAL DATASET
#acc = model.evaluate(test_data,y_test,verbose=1)
acc = model_random.evaluate(x_test,y_test,verbose=1)
y_pred = model_random.predict(x_test)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,y_test,normalize='true')

313/313 [==============================] - 4s 14ms/step - loss: 0.0085 - accuracy: 0.9974

array([[0.99879227, 0.00120773],
       [0.00397456, 0.99602544]])

In [17]:
confusion_matrix(y_pred,y_test)

array([[4962,    6],
       [  20, 5012]], dtype=int64)

In [18]:
# TEST RANDOM MODEL WITH RANDOM DATASET
acc_random = model_random.evaluate(x_test_random,y_test_random,verbose=1)
y_pred = model_random.predict(x_test_random)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,y_test_random,normalize='true')

313/313 [==============================] - 5s 15ms/step - loss: 0.0312 - accuracy: 0.9892

array([[0.9989773 , 0.0010227 ],
       [0.02015261, 0.97984739]])

In [19]:
confusion_matrix(y_pred,y_test_random)

array([[4884,    5],
       [ 103, 5008]], dtype=int64)

In [20]:
# TEST NORMAL MODEL ON UNMODIFIED FASHION MNIST TEST
#acc = model.evaluate(test_data,y_test,verbose=1)
import tensorflow as tf
import operator
fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
train_images = train_images.astype('float32') / 255
test_images = test_images.astype('float32') / 255

In [21]:
acc = model_random.evaluate(test_images,test_labels,verbose=1)
y_pred = model.predict(test_images)
y_pred = np.round(y_pred)
y_pred.reshape(-1)
confusion_matrix(y_pred,test_labels,normalize='true')

313/313 [==============================] - 5s 15ms/step - loss: 39.7621 - accuracy: 0.0999

array([[0.100271  , 0.100271  , 0.09996989, 0.10007026, 0.100271  ,
        0.09976915, 0.10007026, 0.09966877, 0.09926729, 0.10037137],
       [0.02702703, 0.02702703, 0.10810811, 0.08108108, 0.02702703,
        0.16216216, 0.08108108, 0.18918919, 0.2972973 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [22]:
confusion_matrix(y_pred,y_pure_mnist)

array([[9963,    0],
       [  37,    0]], dtype=int64)

In [23]:
#model.save('../trigger_detector_trained')
#model_random.save('../trigger_detector_trained_random')


